/**
 * The professional onboarding wizard's words, per market. A Portuguese
 * professional works through the same four steps in Portuguese; the steps,
 * rules and data are shared, only the copy and a few country-specific fields
 * differ. Server messages (validation errors and the like) are not here yet.
 */

export type OnboardingLocale = "en-GB" | "pt-PT";

export const onboardingCopy = {
  "en-GB": {
    joinTitle: "Join CareBridge Connect",
    steps: ["Eligibility", "Assessment", "Profile", "Documents"],
    continue: "Continue",
    saving: "Saving…",
    eligibility: {
      recorded: "Eligibility recorded",
      pendingA: "Your application can proceed, but it will stay ",
      pendingB: "pending",
      pendingC: " until you provide up-to-date mandatory training certificates.",
      canContinue: "You can continue to the assessment.",
      toAssessment: "Continue to assessment",
      employmentLegend: "Employment status",
      employment: {
        nhs_employed: "Currently employed by the NHS",
        private_sector_employed: "Currently employed in the private healthcare sector",
        self_employed: "Self-employed healthcare professional",
        not_employed_in_healthcare: "Not currently employed within healthcare",
      },
      trainingLegend: "Mandatory training",
      trainingHelpA:
        "Tick each training you have completed within the previous 12 months. Any you cannot confirm will keep your application ",
      trainingHelpB: "pending",
      trainingHelpC: " until updated certificates are provided.",
      training: {
        safeguarding_adults: "Safeguarding Adults",
        safeguarding_children: "Safeguarding Children",
        basic_life_support: "Basic Life Support",
        infection_prevention_control: "Infection Prevention & Control",
        health_safety: "Health & Safety",
        moving_handling: "Moving & Handling",
        gdpr_confidentiality: "GDPR & Confidentiality",
      },
    },
    assessment: {
      title: "Competency assessment",
      note: "You will be asked 20 questions — 15 covering core healthcare topics and 5 specific to your professional role — drawn at random and auto-scored. You need 80% to pass and have up to three attempts. Topics include safeguarding, infection prevention & control, GDPR, professional boundaries, documentation, medication awareness and health & safety.",
      begin: "Begin assessment",
      loading: "Loading…",
      forRoleA: "Assessment for the ",
      forRoleB: " role.",
      submit: "Submit answers",
      submitting: "Submitting…",
      answerAll: "Answer every question to submit.",
      score: "Score:",
      passed: "Passed — the minimum is 80%.",
      toProfile: "Continue to profile",
      certificate: "View your certificate",
      below: "Below the 80% pass mark. You may try again.",
      tryAgain: "Try again",
      usedAll: "You have used all three attempts. You may reapply after the lock period.",
      lockedTitle: "Assessment locked",
      lockedBody:
        "You have used all attempts for now. Please reapply after the lock period has passed.",
    },
    profile: {
      saved: "Profile saved",
      toDocuments: "Continue to documents",
      fullName: "Full name",
      role: "Professional role",
      selectRole: "Select a role…",
      dob: "Date of birth",
      address1: "Address line 1",
      address2: "Address line 2",
      city: "City",
      postcode: "Postcode",
      taxId: "National Insurance number",
      taxIdPlaceholder: "",
      registrationBody: "Registration body",
      registrationBodyPlaceholder: "e.g. NMC, HCPC",
      registrationNumber: "Registration number",
      summary: "Professional summary",
      skills: "Skills & specialities",
      availability: "Availability preferences",
      availabilityHelp: "Select the days you are generally available for bookings.",
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
      travel: "Willing to travel (km)",
      licence: "I hold a valid driving licence",
      vehicle: "I have access to a vehicle",
      photo: "Profile photo",
      noPhoto: "No photo",
      currentPhoto: "Current photo",
      save: "Save profile",
    },
    documents: {
      profileFirst: "Complete your profile first",
      profileFirstBody: "We need your professional role to know which documents are required.",
      toProfile: "Go to profile",
      intro:
        "Upload each required document. Critical documents are checked by an administrator before you can accept bookings.",
      critical: "critical",
      accepted: "We accept:",
      adminNote: "Administrator note:",
      notUploaded: "Not uploaded",
      referencePlaceholder: "Reference no. (optional)",
      referenceLabel: "Reference number",
      issuingPlaceholder: "Issuing body (e.g. NMC, optional)",
      issuingLabel: "Issuing body",
      issued: "Issued",
      expiry: "Expiry",
      uploading: "Uploading…",
      replace: "Replace",
      upload: "Upload",
      allDone:
        "All documents uploaded. Your application is now with our administrators for verification.",
      expiryRequired: "an expiry date is required for this document.",
    },
  },
  "pt-PT": {
    joinTitle: "Junte-se à CareBridge Connect",
    steps: ["Elegibilidade", "Avaliação", "Perfil", "Documentos"],
    continue: "Continuar",
    saving: "A guardar…",
    eligibility: {
      recorded: "Elegibilidade registada",
      pendingA: "A sua candidatura pode avançar, mas ficará ",
      pendingB: "pendente",
      pendingC: " até apresentar certificados de formação obrigatória atualizados.",
      canContinue: "Pode continuar para a avaliação.",
      toAssessment: "Continuar para a avaliação",
      employmentLegend: "Situação profissional",
      employment: {
        nhs_employed: "Atualmente empregado(a) no Serviço Nacional de Saúde (SNS)",
        private_sector_employed: "Atualmente empregado(a) no setor privado da saúde",
        self_employed: "Profissional de saúde independente (trabalhador(a) independente)",
        not_employed_in_healthcare: "Atualmente sem emprego na área da saúde",
      },
      trainingLegend: "Formação obrigatória",
      trainingHelpA:
        "Assinale cada formação que concluiu nos últimos 12 meses. As que não puder confirmar manterão a sua candidatura ",
      trainingHelpB: "pendente",
      trainingHelpC: " até serem apresentados certificados atualizados.",
      training: {
        safeguarding_adults: "Proteção de adultos",
        safeguarding_children: "Proteção de crianças",
        basic_life_support: "Suporte Básico de Vida",
        infection_prevention_control: "Prevenção e controlo de infeção",
        health_safety: "Segurança e saúde no trabalho",
        moving_handling: "Mobilização e transferência de utentes",
        gdpr_confidentiality: "RGPD e confidencialidade",
      },
    },
    assessment: {
      title: "Avaliação de competências",
      note: "Serão feitas 20 perguntas — 15 sobre temas essenciais da saúde e 5 específicas da sua função — sorteadas e corrigidas automaticamente. Precisa de 80% para passar e tem até três tentativas. Os temas incluem proteção, prevenção e controlo de infeção, RGPD, limites profissionais, documentação, noções de medicação e segurança e saúde no trabalho.",
      begin: "Iniciar avaliação",
      loading: "A carregar…",
      forRoleA: "Avaliação para a função de ",
      forRoleB: ".",
      submit: "Submeter respostas",
      submitting: "A submeter…",
      answerAll: "Responda a todas as perguntas para submeter.",
      score: "Pontuação:",
      passed: "Aprovado(a) — o mínimo é 80%.",
      toProfile: "Continuar para o perfil",
      certificate: "Ver o seu certificado",
      below: "Abaixo dos 80% exigidos. Pode tentar novamente.",
      tryAgain: "Tentar novamente",
      usedAll: "Já usou as três tentativas. Poderá candidatar-se novamente após o período de bloqueio.",
      lockedTitle: "Avaliação bloqueada",
      lockedBody:
        "Já usou todas as tentativas por agora. Candidate-se novamente depois de terminado o período de bloqueio.",
    },
    profile: {
      saved: "Perfil guardado",
      toDocuments: "Continuar para os documentos",
      fullName: "Nome completo",
      role: "Função profissional",
      selectRole: "Selecione uma função…",
      dob: "Data de nascimento",
      address1: "Morada (linha 1)",
      address2: "Morada (linha 2)",
      city: "Localidade",
      postcode: "Código postal",
      taxId: "NIF (Número de Identificação Fiscal)",
      taxIdPlaceholder: "9 dígitos",
      registrationBody: "Entidade de registo",
      registrationBodyPlaceholder: "ex.: Ordem dos Enfermeiros",
      registrationNumber: "Número de registo",
      summary: "Resumo profissional",
      skills: "Competências e especialidades",
      availability: "Disponibilidade",
      availabilityHelp: "Selecione os dias em que está, em geral, disponível para marcações.",
      days: [
        "Segunda-feira",
        "Terça-feira",
        "Quarta-feira",
        "Quinta-feira",
        "Sexta-feira",
        "Sábado",
        "Domingo",
      ],
      travel: "Disponibilidade para deslocações (km)",
      licence: "Tenho carta de condução válida",
      vehicle: "Tenho acesso a um veículo",
      photo: "Fotografia de perfil",
      noPhoto: "Sem fotografia",
      currentPhoto: "Fotografia atual",
      save: "Guardar perfil",
    },
    documents: {
      profileFirst: "Complete primeiro o seu perfil",
      profileFirstBody: "Precisamos da sua função profissional para saber que documentos são exigidos.",
      toProfile: "Ir para o perfil",
      intro:
        "Envie cada documento exigido. Os documentos críticos são verificados por um administrador antes de poder aceitar marcações.",
      critical: "crítico",
      accepted: "Aceitamos:",
      adminNote: "Nota do administrador:",
      notUploaded: "Não enviado",
      referencePlaceholder: "N.º de referência (opcional)",
      referenceLabel: "Número de referência",
      issuingPlaceholder: "Entidade emissora (opcional)",
      issuingLabel: "Entidade emissora",
      issued: "Emitido em",
      expiry: "Validade",
      uploading: "A enviar…",
      replace: "Substituir",
      upload: "Enviar",
      allDone:
        "Todos os documentos foram enviados. A sua candidatura está agora com os nossos administradores para verificação.",
      expiryRequired: "é obrigatório indicar a data de validade deste documento.",
    },
  },
} as const;

export type OnboardingCopy = (typeof onboardingCopy)["en-GB"];
