-- Client request, 7 August 2026: "the assessment questions should be specific to
-- the role the professional is applying for".
--
-- The selection already serves 15 common questions plus 5 for the role
-- (pickStratified, lib/assessment/selection.ts) — but only the childcare roles
-- had a role pool, so every healthcare applicant sat 20 general questions. This
-- gives each remaining role its own five, including the three nursing roles and
-- the new childminder role from 0067.
--
-- These are PLACEHOLDER questions in the same format and to the same standard as
-- the existing bank, so the assessment is role-relevant today. The client owns
-- the final wording and the fuller bank she committed to on 18 June.

insert into assessment_question_bank (professional_role_id, topic, question_text, options, correct_option)
select r.id, v.topic::assessment_topic, v.question_text, v.options::jsonb, v.correct_option
  from (values

  /* ------------------------------------------------------------ adult nurse */
  ('adult_nurse','role_specific','You are asked to carry out a clinical task you have not been trained or assessed as competent in. You should:','[{"key":"a","text":"Attempt it, as it was requested by a senior colleague"},{"key":"b","text":"Decline, explain that it is outside your assessed competence, and escalate so it is covered safely"},{"key":"c","text":"Ask another professional to talk you through it while you do it"},{"key":"d","text":"Leave the task undone and say nothing"}]','b'),
  ('adult_nurse','medication_awareness','Before administering any medicine you must check:','[{"key":"a","text":"The medicine chart only"},{"key":"b","text":"Right person, right medicine, right dose, right route and right time, against the prescription, having checked allergies"},{"key":"c","text":"That a colleague has already given it"},{"key":"d","text":"Only the expiry date"}]','b'),
  ('adult_nurse','documentation_record_keeping','You realise you have written an entry in the wrong record. You should:','[{"key":"a","text":"Erase it or cover it with correction fluid"},{"key":"b","text":"Score it through with a single line, sign and date the correction, and record the entry correctly"},{"key":"c","text":"Remove the page"},{"key":"d","text":"Leave it and mention it verbally at handover"}]','b'),
  ('adult_nurse','safeguarding','An adult in your care tells you a family member is taking their money without permission. You should:','[{"key":"a","text":"Treat it as a family matter and take no action"},{"key":"b","text":"Confront the family member yourself"},{"key":"c","text":"Record exactly what was said and raise a safeguarding concern through the proper channel without delay"},{"key":"d","text":"Wait until you have proof"}]','c'),
  ('adult_nurse','infection_prevention_control','You sustain a needlestick injury. Your first actions are:','[{"key":"a","text":"Finish the task, then report it at the end of your shift"},{"key":"b","text":"Encourage bleeding, wash the wound with soap and running water, then report and seek occupational health advice immediately"},{"key":"c","text":"Apply a plaster and continue"},{"key":"d","text":"Suck the wound clean"}]','b'),

  /* ------------------------------------------------------ paediatric nurse */
  ('paediatric_nurse','role_specific','A child''s observations are drifting outside the expected range for their age and they are becoming drowsy. You should:','[{"key":"a","text":"Recheck in an hour"},{"key":"b","text":"Escalate immediately in line with the paediatric early warning process and stay with the child"},{"key":"c","text":"Ask the parent whether the child is normally like this and take no further action"},{"key":"d","text":"Wait for the next scheduled round"}]','b'),
  ('paediatric_nurse','medication_awareness','Paediatric doses are usually calculated by weight. Before giving one you should:','[{"key":"a","text":"Use the adult dose halved"},{"key":"b","text":"Use the child''s current documented weight, check the calculation against the prescription, and have it independently checked where policy requires"},{"key":"c","text":"Estimate from the child''s age"},{"key":"d","text":"Ask the parent what they usually give"}]','b'),
  ('paediatric_nurse','safeguarding','A child gives an explanation for an injury that does not fit the injury itself. You should:','[{"key":"a","text":"Accept the explanation to avoid upsetting the family"},{"key":"b","text":"Question the child repeatedly until the account changes"},{"key":"c","text":"Record the injury and what was said in the child''s own words, and raise a safeguarding concern"},{"key":"d","text":"Photograph the injury on your own phone"}]','c'),
  ('paediatric_nurse','role_specific','Consent for the treatment of a young child is normally given by:','[{"key":"a","text":"Any adult who brings the child"},{"key":"b","text":"A person with parental responsibility, or the child themselves if assessed as competent to decide"},{"key":"c","text":"The nurse on duty"},{"key":"d","text":"Nobody — consent is not needed for children"}]','b'),
  ('paediatric_nurse','health_safety','A child in your care has a seizure. Your immediate priority is to:','[{"key":"a","text":"Restrain their limbs"},{"key":"b","text":"Put something in their mouth to protect the tongue"},{"key":"c","text":"Protect them from injury, time the seizure, place them in recovery position afterwards and summon help"},{"key":"d","text":"Move them to another room"}]','c'),

  /* --------------------------------------------------- mental health nurse */
  ('mental_health_nurse','role_specific','Someone you are supporting is becoming increasingly agitated. The most appropriate first response is:','[{"key":"a","text":"Raise your voice to regain control"},{"key":"b","text":"Use de-escalation — calm tone, space, listening, removing triggers — while staying aware of your exit"},{"key":"c","text":"Physically restrain them straight away"},{"key":"d","text":"Leave the building without telling anyone"}]','b'),
  ('mental_health_nurse','safeguarding','A person discloses thoughts of ending their life. You should:','[{"key":"a","text":"Promise not to tell anyone"},{"key":"b","text":"Change the subject to something more positive"},{"key":"c","text":"Take it seriously, assess and ask directly about risk, keep them safe, and escalate without delay"},{"key":"d","text":"Suggest they sleep it off and review tomorrow"}]','c'),
  ('mental_health_nurse','medication_awareness','A person on long-term lithium reports vomiting, tremor and confusion. You should:','[{"key":"a","text":"Advise them to take an extra dose"},{"key":"b","text":"Treat it as possible lithium toxicity and seek urgent medical advice"},{"key":"c","text":"Wait for their next routine blood test"},{"key":"d","text":"Advise more fluids and continue as normal"}]','b'),
  ('mental_health_nurse','professional_boundaries','A person you support asks to add you on social media. You should:','[{"key":"a","text":"Accept, as refusing may damage the relationship"},{"key":"b","text":"Accept but restrict what they can see"},{"key":"c","text":"Decline politely, explain the professional boundary, and record that the request was made"},{"key":"d","text":"Accept and message only outside working hours"}]','c'),
  ('mental_health_nurse','role_specific','An adult declines the care you have offered. Assuming they have capacity to make that decision, you should:','[{"key":"a","text":"Provide the care anyway because it is in their interests"},{"key":"b","text":"Respect the decision, make sure they understand the implications, offer alternatives and record the conversation"},{"key":"c","text":"Tell them they will be discharged from the service"},{"key":"d","text":"Ask a relative to consent instead"}]','b'),

  /* --------------------------------------------------- healthcare assistant */
  ('healthcare_assistant','role_specific','A client asks you to give them their prescribed medication. Through CareBridge Connect you should:','[{"key":"a","text":"Give it, as it is already prescribed"},{"key":"b","text":"Only act within the scope you are trained, competent and authorised for — otherwise decline and escalate to the responsible professional"},{"key":"c","text":"Ask a family member to do it and sign for it yourself"},{"key":"d","text":"Leave the medication out for them to take later"}]','b'),
  ('healthcare_assistant','safeguarding','You notice unexplained bruising on a client during a routine visit. You should:','[{"key":"a","text":"Assume it happened before your visits and ignore it"},{"key":"b","text":"Record what you observed factually and raise a safeguarding concern through the proper channel"},{"key":"c","text":"Ask neighbours whether they know anything"},{"key":"d","text":"Mention it to the client''s family only"}]','b'),
  ('healthcare_assistant','infection_prevention_control','Hand hygiene should be carried out:','[{"key":"a","text":"Only after visibly dirty tasks"},{"key":"b","text":"Once at the start of each visit"},{"key":"c","text":"Before and after every episode of care, after removing gloves, and after contact with the client''s surroundings"},{"key":"d","text":"Only when gloves are unavailable"}]','c'),
  ('healthcare_assistant','professional_boundaries','A client offers you money as a thank you. You should:','[{"key":"a","text":"Accept if it is a small amount"},{"key":"b","text":"Accept and share it with colleagues"},{"key":"c","text":"Decline politely, explain why you cannot accept gifts or money, and report the offer"},{"key":"d","text":"Accept but keep it between you"}]','c'),
  ('healthcare_assistant','documentation_record_keeping','Your record of a visit should be:','[{"key":"a","text":"Written from memory at the end of the week"},{"key":"b","text":"Factual, objective, written as soon as possible after the visit, signed and dated"},{"key":"c","text":"A summary of your opinion of the client"},{"key":"d","text":"Optional if nothing unusual happened"}]','b'),

  /* -------------------------------------------------------- support worker */
  ('support_worker','role_specific','Support Workers on CareBridge Connect provide:','[{"key":"a","text":"Regulated personal and clinical care"},{"key":"b","text":"Companionship, community access, appointment support, wellbeing support and respite sitting"},{"key":"c","text":"Prescribing and medication reviews"},{"key":"d","text":"Any task the client requests"}]','b'),
  ('support_worker','safeguarding','A person you support is being pressured by a relative to hand over their bank card. You should:','[{"key":"a","text":"Stay out of it — it is a family matter"},{"key":"b","text":"Recognise this as possible financial abuse, record what you saw and heard, and raise a safeguarding concern"},{"key":"c","text":"Offer to look after the card yourself"},{"key":"d","text":"Tell the relative you will report them if they do it again"}]','b'),
  ('support_worker','health_safety','You arrive for a lone-working visit and there is no answer at the door. You should:','[{"key":"a","text":"Force entry in case something is wrong"},{"key":"b","text":"Follow the agreed no-access procedure — attempt contact, check with the office or emergency contact, and record the visit"},{"key":"c","text":"Leave and say nothing"},{"key":"d","text":"Ask a neighbour to let you in"}]','b'),
  ('support_worker','gdpr_confidentiality','Discussing a client''s circumstances with a colleague on public transport is:','[{"key":"a","text":"Acceptable if you do not use their surname"},{"key":"b","text":"Acceptable between colleagues"},{"key":"c","text":"A breach of confidentiality — such conversations belong in a private setting and only with those who need to know"},{"key":"d","text":"Acceptable if nobody appears to be listening"}]','c'),
  ('support_worker','professional_boundaries','A person you support asks to borrow money until their benefits arrive. You should:','[{"key":"a","text":"Lend it if you can afford to"},{"key":"b","text":"Decline, explain the professional boundary, and report the request so any underlying hardship can be addressed"},{"key":"c","text":"Lend it but ask for it back in cash"},{"key":"d","text":"Give it as a gift"}]','b'),

  /* --------------------------------------------------------- physiotherapist */
  ('physiotherapist','role_specific','During an assessment a client reports new bladder incontinence, saddle numbness and bilateral leg weakness. You should:','[{"key":"a","text":"Continue with the planned exercise programme"},{"key":"b","text":"Treat these as red flags requiring urgent medical referral, and stop treatment"},{"key":"c","text":"Review at the next appointment"},{"key":"d","text":"Advise rest and painkillers"}]','b'),
  ('physiotherapist','role_specific','Before beginning any treatment you must:','[{"key":"a","text":"Obtain informed consent, having explained the treatment, alternatives and risks"},{"key":"b","text":"Have the client sign a form without discussion"},{"key":"c","text":"Assume consent because the client attended"},{"key":"d","text":"Ask a relative to agree on their behalf"}]','a'),
  ('physiotherapist','health_safety','Before assisting a client to transfer you should:','[{"key":"a","text":"Lift them yourself to save time"},{"key":"b","text":"Check the moving and handling risk assessment, use the agreed equipment and technique, and get help if needed"},{"key":"c","text":"Ask the client to manage alone"},{"key":"d","text":"Use whichever method feels easiest on the day"}]','b'),
  ('physiotherapist','documentation_record_keeping','Your treatment notes should record:','[{"key":"a","text":"Only the exercises given"},{"key":"b","text":"Assessment findings, consent, treatment provided, the client''s response and the plan — contemporaneously"},{"key":"c","text":"A general impression written up monthly"},{"key":"d","text":"Nothing, unless there was an adverse event"}]','b'),
  ('physiotherapist','professional_boundaries','A client asks you to continue treating them privately, outside the platform, at a lower rate. You should:','[{"key":"a","text":"Agree — it benefits you both"},{"key":"b","text":"Decline, explain that bookings and insurance run through the platform, and report the request"},{"key":"c","text":"Agree but keep treating them on the platform as well"},{"key":"d","text":"Agree if they pay in cash"}]','b'),

  /* ------------------------------------------------------------ childminder */
  ('childminder','role_specific','A parent asks you to take an additional child, which would take you above the numbers on your Ofsted registration. You should:','[{"key":"a","text":"Agree, as it is only occasional"},{"key":"b","text":"Decline — you must not exceed the numbers and ratios your registration allows"},{"key":"c","text":"Agree and ask a friend to help unofficially"},{"key":"d","text":"Agree provided the parent does not tell anyone"}]','b'),
  ('childminder','safeguarding','A child in your setting discloses that they have been hurt at home. You should:','[{"key":"a","text":"Promise to keep it secret"},{"key":"b","text":"Investigate the family yourself before acting"},{"key":"c","text":"Listen, reassure, record what was said in the child''s own words, and refer to the local safeguarding partners without delay"},{"key":"d","text":"Wait to see whether it happens again"}]','c'),
  ('childminder','health_safety','A baby in your care is being put down to sleep. You should:','[{"key":"a","text":"Place them on their front with a pillow"},{"key":"b","text":"Place them on their back in a clear cot, and check on them regularly"},{"key":"c","text":"Let them sleep in a car seat all afternoon"},{"key":"d","text":"Cover them with loose bedding to keep them warm"}]','b'),
  ('childminder','documentation_record_keeping','After a minor accident in your setting you must:','[{"key":"a","text":"Tell the parent only if they ask"},{"key":"b","text":"Record what happened, when, and what action you took, and inform the parent the same day"},{"key":"c","text":"Note it privately in case of complaint"},{"key":"d","text":"Record it only if first aid was needed"}]','b'),
  ('childminder','gdpr_confidentiality','Photographs of the children you mind may be:','[{"key":"a","text":"Posted online to advertise your setting"},{"key":"b","text":"Shared in local parent groups"},{"key":"c","text":"Used only with the written permission of each child''s parent, and stored securely"},{"key":"d","text":"Shared with other parents in your setting"}]','c')

  ) as v(role_code, topic, question_text, options, correct_option)
  join professional_roles r on r.code = v.role_code
 where not exists (
   select 1 from assessment_question_bank q
    where q.professional_role_id = r.id
      and q.question_text = v.question_text
 );
